name: Build and Publish Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic version'
        required: true


jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build Plugin
        run: yarn nx build nx-sonarqube-dotnet

      - name: Publish Plugin
        run: |
          cd dist/packages/nx-sonarqube-dotnet
          npm version ${{ github.event.inputs.version }}
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
